name: 'Merge Conflicts'

on:
  push:
  pull_request_target:
    types:
      - synchronize
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository == 'jellyfin/jellyfin-expo'
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v2.0.1
        with:
          dirtyLabel: 'merge conflict'
          repoToken: ${{ secrets.GH_TOKEN }}
